version: "3.8"

services:
  app:
    container_name: news-management-app
    build:
      context: .
      target: development
    command: yarn start:dev
    ports:
      - "${PORT:-5000}:${PORT:-5000}"
    environment:
      - DATABASE_HOST=mysql_db
      - REDIS_HOST=redis_db
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mysql_db
      - redis_db
    networks:
      - news-network

  mysql_db:
    image: mysql:8.0
    container_name: news_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root_password # root password
      MYSQL_DATABASE: news_management # database to create
      MYSQL_USER: news_user # non-root app user
      MYSQL_PASSWORD: news_password # password for app user
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - news-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis_db:
    image: redis:alpine
    container_name: news-redis
    ports:
      - "6380:6379"
    networks:
      - news-network

volumes:
  mysql_data:

networks:
  news-network:
    driver: bridge
